### PR TITLE
Rails 5.2 support

### PR DESCRIPTION
**Pull request by spdawson**

### CODE REVIEW

**Comment by eitoball** [comment]
@spdawson 

Thank you for your PR. I will merge and cut new version when Rails 5.2.0 is officially released. Before that, could you fix failures in Travis CI? If it is rubocop error, you can temporary ignore to put offending cops into `.rubocop_todo.yml`. Thank you.

**Comment by eitoball** [comment]
@spdawson 

Could you update to rails 5.2 and squash commits into 2 commits; one is for rails 5.2, and the other is for rubocop fixes.

**Comment by spdawson** [comment]
> Could you update to rails 5.2 and squash commits into 2 commits; one is for rails 5.2, and the other is for rubocop fixes.

Done @eitoball

**Comment by eitoball** [comment]
@spdawson Thank you

**Pull request merged**
